use std::sync::Arc;
use uuid::Uuid;
use serde::{Serialize, Deserialize};

use crate::{ModelProfile, Tool};

#[derive(Clone)]
pub enum Message{
    User(UserMessage),
    Assistant(AssistantMessage),
    Tool(ToolMessage),
    Progress(ProgressMessage),
}

#[derive(Debug, Clone)]
pub struct UserMessage {
    pub message: MessageParm,
    pub uuid: Option<String>,
}

impl UserMessage {
    pub fn new(content: impl Into<String>) -> Self {
        UserMessage {
            message: MessageParm {
                content: content.into(),
                role: Role::User,
                name: None,
            },
            uuid: Some(Uuid::new_v4().to_string()),
        }
    }
}

#[derive(Debug, Clone)]
pub struct AssistantMessage {
    //pub model: String,
    pub content: String,
    pub uuid: String,
    pub tool_uses: Option<Vec<ToolUse>>
    //usage: Option<Usage>
}

impl AssistantMessage {
    //pub fn new(model_name: impl Into<String>, content: impl Into<String>) -> Self {
    pub fn new(content: impl Into<String>) -> Self {
        AssistantMessage {
            content: content.into(),
            //model: model_name.into(),
            uuid: Uuid::new_v4().to_string(),
            tool_uses: None,
            //duration_ms: 0,
        }
    }
}

#[derive(Debug, Clone)]
pub struct ToolMessage {
    pub r#type: String,
    pub content: String,
    pub is_error: bool,
    pub tool_use_id: String,
}

impl ToolMessage {
    pub fn from_error(error: impl Into<String>, tool_use_id: impl Into<String>) -> Self {
        Self {
            r#type: "tool_result".to_string(),
            content: error.into(),
            is_error: true,
            tool_use_id: tool_use_id.into(),
        }
    }

    pub fn new_content(content: impl Into<String>, tool_use_id: impl Into<String>) -> Self {
        Self {
            r#type: "tool_result".to_string(),
            content: content.into(),
            is_error: false,
            tool_use_id: tool_use_id.into(),
        }
    }
}

#[derive(Clone)]
pub struct ProgressMessage {
    pub r#type: String,
    pub content: AssistantMessage,
    pub tools: Option<Vec<Arc<dyn Tool>>>,
    pub tool_use_id: Option<String>,
}

#[derive(Debug, Clone)]
pub struct MessageParm {
    pub content: String,
    pub role: Role,
    pub name: Option<String>, // 在同一对话里，用于区分不同对话者
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    System,
    User,
    Assistant,
    Tool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    #[serde(default, deserialize_with = "deserialize_null_as_empty_string")]
    pub content: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_content: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
    pub role: String,
}

/// Deserializes a null value as an empty string.
fn deserialize_null_as_empty_string<'de, D>(deserializer: D) -> Result<String, D::Error>
where
    D: serde::Deserializer<'de>,
{
    use serde::Deserialize;
    Option::<String>::deserialize(deserializer).map(|opt| opt.unwrap_or_default())
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    pub id: String,
    pub r#type: String,
    pub function: Function
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Function {
    pub name: String,
    /// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    pub arguments: String
}

#[derive(Debug, Clone)]
pub struct ToolUse {
    pub id: String,
    pub name: String,
    pub arguments: String,
}

pub struct UnifiedRequest {
    pub model: ModelProfile,
    pub system_prompt: Vec<String>,
    pub messages: Vec<Message>,
    pub tools: Option<Vec<Arc <dyn Tool>>>,
    pub stream: bool,
}